package view.librarian;

import dao.BookDAO;
import controller.CreateAndUpdateBookController;
import exception.BookNotExistException;
import exception.LoanNotExistException;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.Arrays;
import javax.naming.CannotProceedException;
import model.Book;

/**
 *
 * @author alysson
 */
public class LibrarianBooksView extends javax.swing.JFrame {
    
    private BookDAO bookDAO;

    private CreateAndUpdateBookController managementBookController;
    
    private int librarianId;
    
    /**
     * Creates new form LibrarianBooksView
     * @param librarianId
     */
    public LibrarianBooksView(int librarianId) {
        this.librarianId = librarianId;
        this.bookDAO = new BookDAO();
        this.managementBookController = new CreateAndUpdateBookController(librarianId);
        initComponents();
        fillTable();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        titleLabel = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        backButton1 = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        reportButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        titleLabel.setFont(new java.awt.Font("Uroob", 1, 48)); // NOI18N
        titleLabel.setText("LIBRARY APP");

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Book ID", "Book Name", "Book ISBN", "Book Author"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bookTable);
        if (bookTable.getColumnModel().getColumnCount() > 0) {
            bookTable.getColumnModel().getColumn(0).setResizable(false);
            bookTable.getColumnModel().getColumn(1).setResizable(false);
            bookTable.getColumnModel().getColumn(2).setResizable(false);
            bookTable.getColumnModel().getColumn(3).setResizable(false);
        }

        backButton1.setText("Back");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        reportButton.setText("Generate Report");
        reportButton.setToolTipText("");
        reportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(reportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(backButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(460, 460, 460)
                        .addComponent(titleLabel)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titleLabel)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        
        try{
            
            int lineSelected = this.bookTable.getSelectedRow();
            
            String bookId = this.bookTable.getModel().getValueAt(lineSelected, 0).toString();
            
            new AddNewBookView(librarianId, Integer.parseInt(bookId)).setVisible(true);
            
            dispose();
            
        }catch(ArrayIndexOutOfBoundsException e) {
            this.jOptionPane1.showMessageDialog(this,
                "Please, select a book on the grid",
                "Error trying to edit the book",
                jOptionPane1.WARNING_MESSAGE);
        }catch(Exception e){
            this.jOptionPane1.showMessageDialog(this,
                e.getMessage(),
                "Error trying to edit the book",
                jOptionPane1.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_editButtonActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        new LibrarianDashboardView(this.librarianId).setVisible(true);
        dispose();
    }//GEN-LAST:event_backButton1ActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try{
            
            int[] linesSelected = this.bookTable.getSelectedRows();
            
            if(linesSelected.length == 0) {
                throw new ArrayIndexOutOfBoundsException("Please, select a book on the grid");
            }
            
            for(int i = 0; i < linesSelected.length; i++){
                String bookId = this.bookTable.getModel().getValueAt(linesSelected[i], 0).toString();
                this.bookDAO.delete(this.bookDAO.findById(Integer.parseInt(bookId)));
            }

            this.jOptionPane1.showMessageDialog(this,
                "Your book(s) has been deleted!!",
                "Book Status",
                jOptionPane1.INFORMATION_MESSAGE);
               
               new LibrarianBooksView(this.librarianId).setVisible(true);
               dispose();
        }catch (BookNotExistException | HeadlessException | NumberFormatException | CannotProceedException | LoanNotExistException e) {
             this.jOptionPane1.showMessageDialog(this,
                e.getMessage(),
                "Error trying to delete the book",
                jOptionPane1.WARNING_MESSAGE);
        }catch(ArrayIndexOutOfBoundsException e) {
            this.jOptionPane1.showMessageDialog(this,
                e.getMessage(),
                "Error trying to delete the book",
                jOptionPane1.WARNING_MESSAGE);
        }catch (Exception e) {
           this.jOptionPane1.showMessageDialog(this,
                e.getMessage(),
                "Error trying to delete the book",
                jOptionPane1.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void reportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportButtonActionPerformed
        
    }//GEN-LAST:event_reportButtonActionPerformed

    private void fillTable(){
        ArrayList<Book> books = this.bookDAO.get(null);

        for(int i = 0; i < books.size(); i++){

            Book book = books.get(i);
            
            this.bookTable.setValueAt(book.getEntityId(), i, 0);
            this.bookTable.setValueAt(book.getName(), i, 1);
            this.bookTable.setValueAt(book.getIsbn(), i, 2);
            this.bookTable.setValueAt(book.getAuthor(), i, 3);
        }
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton1;
    private javax.swing.JTable bookTable;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reportButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
